version: "3.7"

services:
  backend:
    image: postmodern.alexdaniel.org/alexdaniel-backend:latest
    build:
      context: .
    volumes:
      - /home/alexdaniel/data/alexdaniel/data:/srv/data
      - /home/alexdaniel/data/alexdaniel/logs:/srv/logs
    networks:
      - caddy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first

      labels:
        caddy: alexdaniel.org, www.alexdaniel.org
        caddy.tls: alex.jakimenko+caddy@gmail.com
        caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
